# This is a basic workflow to help you get started with Actions
# This is copied from Modding+ but should work anywhere else

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.8.0
          haxelib install openfl
          haxelib install flixel 4.8.1
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install hscript
          haxelib install newgrounds
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linuxBuild
          path: 'export/release/linux/bin' 
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
      - name: Compile HTML5
        run: haxelib run lime build Project.xml html5
      
      - name: Publish Html5
        uses: actions/upload-artifact@v2
        with:
          name: html5Build
          path: export/release/html5/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.0
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 7.8.0
          haxelib install openfl
          haxelib install flixel 4.8.1
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install hscript
          haxelib install newgrounds
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: export/release/windows/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
      - name: Compile 32 bit
        run: haxelib run lime build windows -D32bit -32
      - name: Publish 32bit
        uses: actions/upload-artifact@v2
        with:
          name: windows32Build
          path: export/32bit/windows/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
  buildMac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.0
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.8.0
          haxelib install openfl
          haxelib install flixel 4.8.1
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install hscript
          haxelib install newgrounds
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macBuild
          path: export/release/macos/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
